# Generated by Django 5.2.7 on 2025-11-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenpedido',
            name='monto_total',
        ),
    ]
