# Generated by Django 5.2.7 on 2025-11-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_ordenpedido_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
