# Generated by Django 5.2.7 on 2025-11-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_ordenpedido_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido')], default='pendiente', max_length=20),
        ),
    ]
