# Generated by Django 5.2.7 on 2025-10-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('precio_compra', models.PositiveIntegerField()),
                ('precio_venta', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('limite_stock', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
