# Generated by Django 5.2.7 on 2025-12-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos/'),
        ),
    ]
