# Generated by Django 5.2.7 on 2025-12-09 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0002_rename_descripcion_repuesto_nombre_repuesto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
    ]
