# Generated by Django 5.2.7 on 2025-11-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
        ('reservas', '0003_remove_disponibilidad_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='reservas.reserva'),
        ),
    ]
