# Generated by Django 5.2.7 on 2025-11-15 04:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Selecciona la fecha exacta de disponibilidad')),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_termino', models.TimeField(default=datetime.time(18, 0))),
                ('duracion_bloque', models.IntegerField(default=30)),
                ('colacion_inicio', models.TimeField(default=datetime.time(13, 0))),
                ('colacion_termino', models.TimeField(default=datetime.time(14, 0))),
                ('activo', models.BooleanField(default=True)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('bloque_inicio', models.TimeField(blank=True, null=True)),
                ('marca_auto', models.CharField(max_length=50)),
                ('modelo_auto', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to='usuarios.usuario')),
                ('disponibilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.disponibilidad')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_mecanico', to='usuarios.usuario')),
                ('servicios', models.ManyToManyField(related_name='reservas', to='servicios.servicio')),
            ],
        ),
    ]
