# Generated by Django 5.2.7 on 2025-10-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('marca_auto', models.CharField(max_length=50)),
                ('modelo_auto', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to='usuarios.usuario')),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_mecanico', to='usuarios.usuario')),
                ('servicios', models.ManyToManyField(related_name='reservas', to='servicios.servicio')),
            ],
        ),
    ]
