# Generated by Django 5.2.7 on 2025-11-03 23:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('usuarios', '0003_alter_usuario_options_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bloque_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_mecanico', to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=15)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_termino', models.TimeField(default=datetime.time(18, 0))),
                ('duracion_bloque', models.IntegerField(default=30)),
                ('colacion_inicio', models.TimeField(default=datetime.time(13, 0))),
                ('colacion_termino', models.TimeField(default=datetime.time(14, 0))),
                ('activo', models.BooleanField(default=True)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.disponibilidad'),
        ),
    ]
