# Generated by Django 5.2.7 on 2025-11-06 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_bloque_inicio_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha',
            field=models.DateField(default=datetime.date.today, help_text='Selecciona la fecha exacta de disponibilidad'),
            preserve_default=False,
        ),
    ]
